In [1]:
import csv
import pandas as pd
import numpy as np
from collections import defaultdict
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Train Model

In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [6]:
data = pd.read_csv("/content/drive/MyDrive/Solving For India Hackathon/Converted_Data_model.csv")

In [7]:
data

Disease  abdomen acute  abdominal bloating  \
0       accident cerebrovascular              0                   0   
1                 adenocarcinoma              0                   0   
2                       adhesion              0                   0   
3                  affect labile              0                   0   
4            Alzheimer's disease              0                   0   
..                           ...            ...                 ...   
133         effusion pericardial              0                   0   
134                   septicemia              0                   0   
135            carcinoma of lung              0                   0   
136           carcinoma prostate              0                   0   
137  upper respiratory infection              0                   0   

     abdominal tenderness  abnormal sensation  abnormally hard consistency  \
0                       0                   0                            0   
1                       0                   0                            0   
2                       0                   0                            0   
3                       0                   0                            0   
4                       0                   0                            0   
..                    ...                 ...                          ...   
133                     0                   0                            0   
134                     0                   0                            0   
135                     0                   0                            0   
136                     0                   0                            0   
137                     0                   0                            0   

     abortion  abscess bacterial  absences finding  achalasia  ...  \
0           0                  0                 0          0  ...   
1           0                  0                 0          0  ...   
2           0                  0                 0          0  ...   
3           0                  0                 0          0  ...   
4           0                  0                 0          0  ...   
..        ...                ...               ...        ...  ...   
133         0                  0                 0          0  ...   
134         0                  0                 0          0  ...   
135         0                  0                 0          0  ...   
136         0                  0                 0          0  ...   
137         0                  0                 0          0  ...   

     vision blurred  vomiting  weepiness  weight gain  welt  wheelchair bound  \
0                 0         0          0            0     0                 0   
1                 0         0          0            0     0                 0   
2                 0         1          0            0     0                 0   
3                 0         0          0            0     0                 0   
4                 0         0          0            0     0                 1   
..              ...       ...        ...          ...   ...               ...   
133               0         0          0            0     0                 0   
134               0         0          0            0     0                 0   
135               0         0          0            0     0                 0   
136               0         0          0            0     0                 0   
137               0         0          0            0     0                 0   

     wheezing  withdraw  worry  yellow sputum  
0           0         0      0              0  
1           0         0      0              0  
2           0         0      0              0  
3           0         0      0              0  
4           0         0      0              0  
..        ...       ...    ...            ...  
133         0         0      0              0  
134         0         0      0       

In [12]:
from google.colab import files
y_train=data["Disease"]
X_train = data.iloc[:,1:]
y_test = "HIV"
X_test = [data.iloc[1, 1:]]

In [14]:
y_train

0         accident cerebrovascular
1                   adenocarcinoma
2                         adhesion
3                    affect labile
4              Alzheimer's disease
                  ...             
133           effusion pericardial
134                     septicemia
135              carcinoma of lung
136             carcinoma prostate
137    upper respiratory infection
Name: Disease, Length: 138, dtype: object

In [15]:
X_train

abdomen acute  abdominal bloating  abdominal tenderness  \
0                0                   0                     0   
1                0                   0                     0   
2                0                   0                     0   
3                0                   0                     0   
4                0                   0                     0   
..             ...                 ...                   ...   
133              0                   0                     0   
134              0                   0                     0   
135              0                   0                     0   
136              0                   0                     0   
137              0                   0                     0   

     abnormal sensation  abnormally hard consistency  abortion  \
0                     0                            0         0   
1                     0                            0         0   
2                     0                            0         0   
3                     0                            0         0   
4                     0                            0         0   
..                  ...                          ...       ...   
133                   0                            0         0   
134                   0                            0         0   
135                   0                            0         0   
136                   0                            0         0   
137                   0                            0         0   

     abscess bacterial  absences finding  achalasia  ache  ...  \
0                    0                 0          0     0  ...   
1                    0                 0          0     0  ...   
2                    0                 0          0     0  ...   
3                    0                 0          0     0  ...   
4                    0                 0          0     0  ...   
..                 ...               ...        ...   ...  ...   
133                  0                 0          0     0  ...   
134                  0                 0          0     0  ...   
135                  0                 0          0     1  ...   
136                  0                 0          0     0  ...   
137                  0                 0          0     0  ...   

     vision blurred  vomiting  weepiness  weight gain  welt  wheelchair bound  \
0                 0         0          0            0     0                 0   
1                 0         0          0            0     0                 0   
2                 0         1          0            0     0                 0   
3                 0         0          0            0     0                 0   
4                 0         0          0            0     0                 1   
..              ...       ...        ...          ...   ...               ...   
133               0         0          0            0     0                 0   
134               0         0          0            0     0                 0   
135               0         0          0            0     0                 0   
136               0         0          0            0     0                 0   
137               0         0          0            0     0                 0   

     wheezing  withdraw  worry  yellow sputum  
0           0         0      0              0  
1           0         0      0              0  
2           0         0      0              0  
3           0         0      0              0  
4           0         0      0              0  
..        ...       ...    ...            ...  
133         0         0      0              0  
134         0         0      0              0  
135         0         0      0              0  
136         0         0      0              0  
137         1         0      0              0  

[138 rows x 400 columns]

In [16]:
X_test

[abdomen acute                  0
 abdominal bloating             0
 abdominal tenderness           0
 abnormal sensation             0
 abnormally hard consistency    0
                               ..
 wheelchair bound               0
 wheezing                       0
 withdraw                       0
 worry                          0
 yellow sputum                  0
 Name: 1, Length: 400, dtype: object]

In [18]:
test = data.iloc[1, 1:]
print(test[77])
test[77] = False
X_test = [test]

0


In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(metric = 'jaccard')
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(metric='jaccard')

In [26]:
knn_clf.predict(X_test)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/pairwise.py:2025: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


array(['adenocarcinoma'], dtype=object)

In [55]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.6)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
score = knn.score(X_test, y_test)
print("Model score:", score)

Model score: 0.9888888888888889


In [66]:
 # Replace with your own set of symptoms
distances, indices = knn.kneighbors(X_test, n_neighbors=5)

# Print the 5 nearest neighbors
print('5 Nearest Neighbors:')
print('Nearest Neighbors:')
for index in indices:
    print(X_train[index])
    print('Disease:', y_train[index])

5 Nearest Neighbors:
Nearest Neighbors:
[[6.3 2.5 5.  1.9]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.5 1.8]
 [6.3 2.8 5.1 1.5]
 [6.7 3.  5.  1.7]]
Disease: [2 2 2 2 1]
[[6.2 2.8 4.8 1.8]
 [6.3 2.5 5.  1.9]
 [6.3 2.5 4.9 1.5]
 [6.3 2.8 5.1 1.5]
 [6.7 3.  5.  1.7]]
Disease: [2 2 1 2 1]
[[5.2 3.4 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.4 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.4 1.5 0.2]]
Disease: [0 0 0 0 0]
[[6.7 3.1 5.6 2.4]
 [6.7 3.3 5.7 2.1]
 [6.7 3.3 5.7 2.5]
 [6.8 3.  5.5 2.1]
 [6.5 3.  5.8 2.2]]
Disease: [2 2 2 2 2]
[[4.7 3.2 1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.6 3.4 1.4 0.3]
 [4.8 3.  1.4 0.3]
 [4.8 3.  1.4 0.1]]
Disease: [0 0 0 0 0]
[[7.3 2.9 6.3 1.8]
 [7.2 3.2 6.  1.8]
 [6.7 2.5 5.8 1.8]
 [6.7 3.3 5.7 2.1]
 [6.8 3.  5.5 2.1]]
Disease: [2 2 2 2 2]
[[5.7 4.4 1.5 0.4]
 [5.7 3.8 1.7 0.3]
 [5.4 3.7 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]]
Disease: [0 0 0 0 0]
[[5.4 3.7 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.4 1.5 0.2]]
Disease: [0 0 0 0 0]
[[6.2 2.8 4.8 1.8]
 [6.3

In [67]:
from flask import Flask, request
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

app = Flask(__name__)
def predict_disease(symptoms):
    #print(symptoms_dict)
    data = pd.read_csv(r"/content/drive/MyDrive/Solving For India Hackathon/Converted_Data_model.csv")
    y_train=data["disease"]
    X_train = data.iloc[:,1:]
    y_test = "HIV"

    symptoms_dict = data.iloc[0:0, 1:]
    symptoms_dict = symptoms_dict.to_dict()


    for keys in symptoms_dict:
        symptoms_dict[keys] = 0.0

    for symptom in symptoms:
        symptoms_dict[symptom] = 1.0
        print(symptoms_dict[symptom])
        print(symptoms_dict)
    
    
   
    X_test = [list(symptoms_dict.values())]
    
    #X_test = pd.DataFrame(symptoms_dict, index=[0], columns=X_train.columns)
    knn_clf = KNeighborsClassifier()
    knn_clf.fit(X_train,y_train)
    distance, prediction = knn_clf.kneighbors(X_test, n_neighbors=10)
    que = []
    for i in prediction:
        que.append(y_train.iloc[i])
   
    #prediction = knn_clf.predict(X_test)
    return que

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        symptoms = request.form['symptoms'].split(",")
       
        prediction = predict_disease(symptoms)
        return f"Predicted disease: {prediction}"
    return '''
        <form method="post">
            Symptoms : <input type="text" name="symptoms"><br>
            <input type="submit" value="Submit"><br>
        </form>
    '''
if __name__ == '__main__':
  app.run()

 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
